### ISSUE TITLE
segmentation fault when running with node_id value and debug mode

### ISSUE THREAD

**Issue by sothy** [travelping/vpp#24]
I'm running vpp20.01 with upf plugin and assigned node id within a code. After running,it gives segmentaiton fault. I need to remove the code here:

static void
 free_node_id (void *p)
 {
-  pfcp_node_id_t *v = p;
+  //pfcp_node_id_t *v = p;
 
-  vec_free (v->fqdn);
+  //vec_free (v->fqdn);
 }
here node id does not have fqdn so it seems uninitalised variable.isnt it?

**Comment by RoadRunnr** [comment]
What exactly do you mean by "assigned node id within a code"? Did you send a PFCP message with a Node-Id IE (can you share the PFCP message as PCAP?) or did you modify the UPF code?

**Comment by sothy** [comment]
I did the following changes in order to send node id-IE.
 git diff src/plugins/upf/upf_pfcp_api.c
diff --git a/src/plugins/upf/upf_pfcp_api.c b/src/plugins/upf/upf_pfcp_api.c
index 96aa4ea77..473632c41 100644
--- a/src/plugins/upf/upf_pfcp_api.c
+++ b/src/plugins/upf/upf_pfcp_api.c
@@ -478,6 +478,17 @@ handle_association_setup_request (sx_msg_t * req,
 
   init_response_node_id (&resp.response);
 
++  ip46_address_t node_ip;
++  node_ip.ip4.as_u8[0] =172;
++  node_ip.ip4.as_u8[1] =32;
++  node_ip.ip4.as_u8[2] =1;
++  node_ip.ip4.as_u8[3] =2;

++  SET_BIT(resp.grp.fields, ASSOCIATION_SETUP_RESPONSE_NODE_ID);
++  resp.response.node_id.type=NID_IPv4;
++  resp.response.node_id.ip=node_ip;


   SET_BIT (resp.grp.fields, ASSOCIATION_SETUP_RESPONSE_RECOVERY_TIME_STAMP);
   resp.recovery_time_stamp = sx->start_time;
