### ISSUE TITLE
upf_buffer_opaque gtpu flags two assigned in a single function

### ISSUE THREAD

**Issue by sothy** [travelping/vpp#25]
In line [313 ](https://github.com/travelping/vpp/blob/feature/2001/upf/src/plugins/upf/gtpu_decap.c#L313)of gtpu_decap.c and  line [318](https://github.com/travelping/vpp/blob/feature/2001/upf/src/plugins/upf/gtpu_decap.c#L318) assignes upf_buffer_opaque(b)->gtpu.flags one by one differently. I wonder it is possible to delete one line?

**Comment by RoadRunnr** [comment]
They could be merged, but I don't see that as a priority.

It is possible that the compiler sees this and merges them already for the release builds.

**Comment by RoadRunnr** [comment]
Turns out this is actually a real bug, the flags can collide.
