### ISSUE TITLE
UE_IP_ADDRESS without IE_UE_IP_ADDRESS_SD=1

### ISSUE THREAD

**Issue by sothy** [travelping/vpp#26]
Hi,
My SMF sends PFCP session modification request with create_pdr.pdi.UEIP address.
This create_pdr has to detect the downlink flow based on UE ip address.  In one setup, I didnt set UE as destination address. Anyhow, it was a problem of SMF. However, UPF sends a  reply of  PFCP session modification response with success. In this case, there is no entry in VRF 2  to process the downlink packet.  
To be complete, UPF needs to send error message of "Semantically incorrect Information Element" in PFCP session modification response. 

Am I right? It is not an urgent feature, but I prefer to keep an entry in the issue list.

**Comment by yongshouwang** [comment]
Hello, I am a member of the oai project team and are working on your open source project featrure / 2001 / upf. During the research, I have the following questions:
1. The tests passed those PFCP protocols;
2. What effect did the test achieve? gtpu encap, decap, or forward traffic;
3. If the pfcp protocol is issued, user traffic can be normally forwarded, discarded, cached, etc. according to the PFCP protocol;
4.upf 2001 This project, how do you test, please give a test topology diagram;

thank you very much!

**Comment by RoadRunnr** [comment]
> Hello, I am a member of the oai project team and are working on your open source project featrure / 2001 / upf. During the research, I have the following questions:

@yongshouwang **stop spamming** unrelated issues with your questions. Open a new issue (and only one) with you questions.

**Comment by yongshouwang** [comment]
hello:
     feature/2001/upf,  how do you test, can far traffic,  please give a test topology diagram;
    thank you very much!

**Comment by RoadRunnr** [comment]
@sothy after considering this a bit more I can't see why this setting would be invalid.

The fact that this creates a combination of filters that does not permit traffic to pass is IMHO not relevant when checking the PFCP message. It is the responsibility for the PGW-C/SMF instance to make sure the message when considered as a whole is consistent.

I also don't see anything in specifications that would prohibit this combination of flags.
Especially TS 23.214, Table  5.2.2-1 does not limit the use of UE IP Address to any specific direction.
Within the PDI, the combination of Source Interface `CORE` and UE IP address set to `DESTINATION` seems to be valid. At the PDR or PDI level there is no notion of UL or DL, this is only assigned at the URR level when considering both PDR and FAR.

**Comment by sothy** [comment]
@RoadRunnr  yes you are right. It is responsibility of PGW-X/SMF.  

Here UE IP address **does not set DESTINATION** based on your second paragraph . cant UPF reject or give error message?

**Comment by RoadRunnr** [comment]
> Here UE IP address **does not set DESTINATION** based on your second paragraph . cant UPF reject or give error message?

On what basis? Source and Destination UE IPs are permitted in PDI. I can't see any information in the PDI that would make either one invalid.

**Comment by sothy** [comment]
@RoadRunnr Make sure that we running two separate threads. For this one, I didnt post my show upf session message.  When I do test again, I will post the message here later in the week. 

In the other thread, I posted the correct upf session info. Since I remove the logic to use SDF, I'm forced to use pdr id into opaque field. so that I can make flow.
