### ISSUE TITLE
how to test upf  ?

### ISSUE THREAD

**Issue by yongshouwang** [travelping/vpp#31]
Hello :
         I am a member of the Oai project team, and is working on feature / 2001 / upf. I have the following questions, please answer them. Thank you! Questions are as follows:
       The effect of the upf test? Is the control instruction issued through the pfcp protocol, and upf performs the forwarding and discards? How to test? Can you draw a test topology?
        thank you very much! !! !!

**Comment by yongshouwang** [comment]
hello:
        What is the role of the init.conf configuration in the upf project? Can you draw a flowchart?
        thank you very much!

**Comment by RoadRunnr** [comment]
> hello:
>         What is the role of the init.conf configuration in the upf project? Can you draw a flowchart?
>         thank you very much!

The init.conf (and startup.conf) is part of the normal VPP config. We do not have the resource to provide generic VPP support, please address those issue to the upstream project.

**Comment by RoadRunnr** [comment]
> Hello :
>          I am a member of the Oai project team, and is working on feature / 2001 / upf. I have the following questions, please answer them. Thank you! Questions are as follows:
>        The effect of the upf test?

I don't understand that question. Anyhow, tests are very limited at the moment. Only a few PFCP interactions are tested.

> Is the control instruction issued through the pfcp protocol, and upf performs the forwarding and discards?

Yes.

> How to test?

Deploy UPF with PGW-C or SMF, run test manually.

> Can you draw a test topology?

Manual tests involve deploying a full EPC core manually, 3GPP TS 23.214 Section 4.1 for a typical EPC setup with PGW-C and UPF.
Automated tests (as part of CI) are somewhat experimental. Look at .gitlab-ci.yaml for how they are executed.

>         thank you very much! !! !!

**Comment by yongshouwang** [comment]
hello:
      Thank you in advance for your reply!
Thank you in advance for your reply!
I am preparing to test traveling upf, researched the init.conf startup.conf configuration file, and have the following problems:
1.SMF sends the PFCP protocol to the UPF. Which network port is used by the init.conf configuration file?
2.Simulate user streaming, which network port is through the init.conf configuration file?

thank you very much!

**Comment by yongshouwang** [comment]
hello:
First, Thank you in advance for your reply!
I have the following 3 questions, please answer them. The questions are as follows:

Question 1:
What is the meaning of the configuration commands contained in init.conf?

Question 2:
ip route add 0.0.0.0/0 table 2 via 172.20.16.1 host-ens161
Which interface is 172.20.16.1 in this configuration command?

Question 3: What does the following command mean?

upf pfcp endpoint ip 172.21.16.1 vrf 0
upf nwi name cp vrf 0
upf nwi name epc vrf 1
upf nwi name sgi vrf 2

upf gtpu endpoint ip 172.21.16.1 nwi cp teid 0x80000000 / 2
upf gtpu endpoint ip 172.20.16.105 nwi epc teid 0x80000000 / 2


thank you very much!

**Comment by zhonglin6666** [comment]
> > Hello :
> >          I am a member of the Oai project team, and is working on feature / 2001 / upf. I have the following questions, please answer them. Thank you! Questions are as follows:
> >        The effect of the upf test?
> 
> I don't understand that question. Anyhow, tests are very limited at the moment. Only a few PFCP interactions are tested.
> 
> > Is the control instruction issued through the pfcp protocol, and upf performs the forwarding and discards?
> 
> Yes.
> 
> > How to test?
> 
> Deploy UPF with PGW-C or SMF, run test manually.
> 
> > Can you draw a test topology?
> 
> Manual tests involve deploying a full EPC core manually, 3GPP TS 23.214 Section 4.1 for a typical EPC setup with PGW-C and UPF.
> Automated tests (as part of CI) are somewhat experimental. Look at .gitlab-ci.yaml for how they are executed.
> 
> > thank you very much! !! !!

cp interface:  Communication with SMF with PFCP protocol
epc interface:  mainly for 4G ?
sig interface: ?

Can you give me A little explanation ？  Thx!
