### ISSUE TITLE
test_upf.py

### ISSUE THREAD

**Issue by yongshouwang** [travelping/vpp#32]
hi,
      feature /2001 /upf project file: test_upf.py,   how is it executed, how to test upf?
       thank you very much!

**Comment by orion-belt** [comment]
Check make options
`make test TEST=test_upf V=2`

**Comment by rohan-kharade** [comment]
Check make options. You can use test as below -
`make test TEST=test_upf V=2`

**Comment by ivan4th** [comment]
@rohan-kharade yes, that's correct way to do it. Thanks
