### ISSUE TITLE
UPF's features support

### ISSUE THREAD

**Issue by Qdieyou** [travelping/vpp#33]
Do you have a description upf specific support features, the more detailed the better!
Thank you!

**Comment by RoadRunnr** [comment]
https://github.com/travelping/vpp/blob/feature/2005/upf/src/plugins/upf/README.md

Not sure how much more detailed makes sense.

**Comment by Qdieyou** [comment]
Do we have any more details? 
For example, How many IEs are supported, and supported lists?
