### ISSUE TITLE
unable to set pfcp endpint

### ISSUE THREAD

**Issue by rohan-kharade** [travelping/vpp#36]
Hello,
I am unable to set pfcp endpoint in docker image used for test. Am I missing the syntax ?
```
DBGvpp# upf pfcp endpoint ip 172.21.16.1 vrf 0
upf pfcp endpoint ip: vnet_upf_pfcp_endpoint_add_del -8
DBGvpp# show upf pfcp endpoint                
Endpoints: 0
DBGvpp# show upf pfcp endpoint ip
show upf pfcp endpoint: parse error `ip'
DBGvpp# 
```

**Comment by RoadRunnr** [comment]
Seems the show command does not work as expected.

**Comment by RoadRunnr** [comment]
> I am unable to set pfcp endpoint in docker image used for test. Am I missing the syntax ?

MIssed that bit, sorry. Your syntax is correct.The IP has to exist in selected VRF and the command can only be issued once for a single IP.

Can you show the rest of you config?

**Comment by rohan-kharade** [comment]
@RoadRunnr 
The command configures pfcp endpoint. I am able to insert sessions and can verify it. Only thing is `show upf pfcp endpoint` gives weired output.

I am using default init.conf.
