### ISSUE TITLE
About GTPU unpacking and packing?

### ISSUE THREAD

**Issue by w910820618** [travelping/vpp#38]
I cloned the code under the two branches of feature / 2001 / upf and feature / 2005 / upf, and found that neither gtpu can be unpacked.
I want to ask two questions：
1. Which branch can currently unpack GTPU?
2. If there is no branch that supports GTPU unpacking now, do you have any plans to support it?
Thank you very much for your contribution to the open source community！！！

**Comment by rohan-kharade** [comment]
This is already answered in [last issue](https://github.com/travelping/vpp/issues/34). Upf plugin handles it.

Run upf. (make sure networking in `init.conf`, sample test can help to understand)
Try to send gtpu ecapsulated packet directly to upf and use `show trace`. Note `upf-gtpu4-input`  graph node as in below sample trace. Similarly, for encap you can see node `upf4-encap`.


```
DBGvpp# show trace
------------------- Start of thread 0 vpp_main -------------------
Packet 1
00:00:37:940808: af-packet-input
  af_packet: hw_if_index 1 next-index 4
    tpacket2_hdr:
      status 0x1 len 110 snaplen 110 mac 66 net 80
      sec 0x5e94dcd4 nsec 0x1f507b24 vlan 0 vlan_tpid 0
00:00:37:946619: ethernet-input
  IP4: 1e:36:e5:e6:5f:89 -> 00:0c:29:46:1f:53
00:00:37:947727: ip4-input
  UDP: 172.20.16.3 -> 172.20.16.2
    tos 0x00, ttl 64, length 96, checksum 0x025f dscp CS0 ecn NON_ECN
    fragment id 0x0001
  UDP: 2152 -> 2152
    length 76, checksum 0x10b2
00:00:37:948867: ip4-lookup
  fib 1 dpo-idx 25 flow hash: 0x00000000
  UDP: 172.20.16.3 -> 172.20.16.2
    tos 0x00, ttl 64, length 96, checksum 0x025f dscp CS0 ecn NON_ECN
    fragment id 0x0001
  UDP: 2152 -> 2152
    length 76, checksum 0x10b2
00:00:37:949553: ip4-local
    UDP: 172.20.16.3 -> 172.20.16.2
      tos 0x00, ttl 64, length 96, checksum 0x025f dscp CS0 ecn NON_ECN
      fragment id 0x0001
    UDP: 2152 -> 2152
      length 76, checksum 0x10b2
00:00:37:949571: ip4-udp-lookup
  UDP: src-port 2152 dst-port 2152
00:00:37:949998: upf-gtpu4-input               ########## Note this, its gtpu decap ##########
  GTPU decap error - session for teid 0x000004d2 does not exist.   ### session needed ###
00:00:37:950528: error-drop
  rx:host-n3
00:00:37:951179: drop
  upf-gtpu4-input: no such tunnel packets
```
In 2005 branch, graph nodes are different as file attached below
![image](https://user-images.githubusercontent.com/8424021/79325549-a35a5800-7f11-11ea-8435-eebb15be1ce1.png)

**Comment by w910820618** [comment]
@rohan-kharade Can you share your test program?

**Comment by w910820618** [comment]
@rohan-kharade **How did you create the gtpu tunnel?**

**Comment by w910820618** [comment]
@rohan-kharade Can you share the pfcp message you sent to me?

**Comment by w910820618** [comment]
![918614c51b599ab9e982d08b57e4b76](https://user-images.githubusercontent.com/22961061/80297014-0372b900-87b2-11ea-9a26-996c06b055ad.png)

**Comment by w910820618** [comment]
![image](https://user-images.githubusercontent.com/22961061/80297141-2487d980-87b3-11ea-8802-fbda31ecb557.png)
My session index is -1, do you know why?

**Comment by w910820618** [comment]
This is my log file
[log.txt](https://github.com/travelping/vpp/files/4534973/log.txt)
