### ISSUE TITLE
About test_upf test case

### ISSUE THREAD

**Issue by w910820618** [travelping/vpp#39]
In the 20.01-157 ~ g1e7bebde5-dirty version of vpp, I did not pass the following test cases in test_upf：
https://github.com/travelping/vpp/blob/d5c9f33d25ddfec919a24a6bcca7a2e2c1527863/src/plugins/upf/test/test_upf.py#L95
https://github.com/travelping/vpp/blob/d5c9f33d25ddfec919a24a6bcca7a2e2c1527863/src/plugins/upf/test/test_upf.py#L97
https://github.com/travelping/vpp/blob/d5c9f33d25ddfec919a24a6bcca7a2e2c1527863/src/plugins/upf/test/test_upf.py#L98

After logging out
https://github.com/travelping/vpp/blob/d5c9f33d25ddfec919a24a6bcca7a2e2c1527863/src/plugins/upf/test/test_upf.py#L96,I found that forwarding is still successful。But I tested in the 20.01-159 ~ g78f2440-dirty version and found that the test cases can run successfully.Do you have updated the code and added the function of processing pfcp protocol?

**Comment by rohan-kharade** [comment]
Try to refer or add comment when you close issue so that it will be helpful for others.
