### ISSUE TITLE
Questions about the establishment of gtpu tunnel

### ISSUE THREAD

**Issue by w910820618** [travelping/vpp#49]
A new interface is created in vpp, and the gtpu tunnel is created through the command line
![image](https://user-images.githubusercontent.com/22961061/80180010-5a528400-8634-11ea-867a-2d7446e681a0.png)

I modified the verify_forwarding function in the test_upf.py file, which encapsulates a gtpu packet.
![image](https://user-images.githubusercontent.com/22961061/80179867-0cd61700-8634-11ea-9779-8323ebd0c5f0.png)

The log shows that I have created a tunnel and the teid of the tunnel is set to 2.
![image](https://user-images.githubusercontent.com/22961061/80180494-71de3c80-8635-11ea-97cb-407a36784b30.png)

Why does it prompt me that the teid in the gtpu packet is not found
![image](https://user-images.githubusercontent.com/22961061/80180606-b8339b80-8635-11ea-86d3-57134e89729f.png)

This is the log file I generated after testing.
[log.txt](https://github.com/travelping/vpp/files/4526936/log.txt)

**Comment by rohan-kharade** [comment]
Did you add pfcp session for that teid ?
can you show output of `show upf session`

**Comment by RoadRunnr** [comment]
The screenshot shows an interaction with the GTPU plugin. This repository and issue tracker only deal with the UPF plugin.
Please ask the VPP community for help when you have problems with the GTPU plugin.
