### ISSUE TITLE
ue ip is ignored from PDI

### ISSUE THREAD

**Issue by rohan-kharade** [travelping/vpp#50]
Here somehow ue IP is ignored from PDI. As it can be seen in trace, ue ip is 20.10.10.10 and PDI rule is for 10.10.10.10. Is it because of ACL `any to any` ?

<img width="1545" alt="Screenshot 2020-04-24 at 15 46 16" src="https://user-images.githubusercontent.com/8424021/80220015-87f2f980-8643-11ea-8eb3-7954e5a5ae35.png">

**Comment by RoadRunnr** [comment]
> Here somehow ue IP is ignored from PDI. As it can be seen in trace, ue ip is 20.10.10.10 and PDI rule is for 10.10.10.10. Is it because of ACL `any to any` ?

Well, `any to any` means exactly what is says, permit any traffic to any other endpoint. If you want to match for the UE IP, you have to use `any to assigned`.

I'm not even sure that `any to any` is a valid ACL. The specifications are somewhat fuzzy on that. 3GPP TS 29.244 says:

> The Flow Description field, when present, shall be encoded as an OctetString as specified in clause 5.4.2 of 3GPP TS 29.212 [8].

and 3GPP TS 29.212 has a very restrictive definition of the content of that field.
