### ISSUE TITLE
source interface vs network instance

### ISSUE THREAD

**Issue by sothy** [travelping/vpp#57]
Hello,
I didnt understand source interface and network instance in 29.244 and UPF implementation.

When I defined UPF, I defined a network instance with DNN (for core interface). SMF automatically considers of Sgi network instances. According to current UPF implementation.

so I defined I-UPF, I defined two network instance (core and accees). It works.   

I'm confused what need to be defined as source interface and network instance?

**Comment by RoadRunnr** [comment]
Sothy, I can not explain the 3GPP specifications for everyone. This issue tracker is about the implementation. When you think the implementation does not what the specifications says, then please explain how you understand the specification and why (with proper reasoning), and explain what the VPP/UPF plugin should do differently.

Anyhow:

`Network Instance` is a name given to an IP network. In normal routers this would often be called a VRF. You can choose whatever name you want.
`Source Interface` can only take 4 values (Access, Core, SGi-LAN/N6-LAN, CP-function).

According to 3GPP TS 29.244 is Source Interface not part of the parameters to match. Clause 5.2.1A.1 says:

> When provisioning a PDR in the UP function, the CP function shall provide the PDI with the following information:
> - the source interface of the incoming packets;
> - a combination of the parameters, that incoming packets **are requested to match**, among: Local F-TEID, Network Instance, UE IP address, SDF Filter(s) and/or Application ID. [...] [emphasis added]

So, Source Interface is only a **_information_** not a **_match_**. This information is used together with the Destination Interface in FAR to determine the traffic direction for URR processing.

**Comment by sothy** [comment]
@RoadRunnr  sorry for making you nervous. 

I'm talking of source interface in User Plane IP Resource Information.  
3GPP TS 29.244 v15.5.0, says 

> shall contain a Source Interface value as encoded in octet 5 of the Figure 8.2.2-1 in subclause 8.2.2, identifying the Source Interface with which the IP address or TEID Range is associated.

> 
In my I-UPF, I should include  Access and core interface with IP address and TEID, rather than network instance. Not sure, thats why I asked you. Today, I used access and core as network instance. It worked.  

I thought DNN name should be same as network instance name. 
Either we interpret something different or I'm wrong or I missed the purpose of source interface field in User Plane IP Resource Information.
