### ISSUE TITLE
Port numbers in SDF filters are swapped between src and dst for DL traffic

### ISSUE THREAD

**Issue by fdangtran** [travelping/vpp#59]
For DL traffic, a SDF filter such as:
`permit out ip from 0.0.0.0/0 102 to assigned 53`
is handled as if it was:
`permit out ip from 0.0.0.0/0 53 to assigned 102`
A copy-and-paste error in lines 1477-78 ?
https://github.com/travelping/vpp/blob/85c09c8644665cb517249d82b5765e3a2e1438b7/src/plugins/upf/upf_pfcp.c#L1461-L1481

**Comment by RoadRunnr** [comment]
Yes, that looks wrong.
