### ISSUE TITLE
Where to find upf plugin documentation?

### ISSUE THREAD

**Issue by Twig96** [travelping/vpp#70]
Hi, I'm new to vpp and I spent sometime to figure out what it allows to do following the fd.io tutorial steps. I would now focus on what this version of vpp add to the original one and how to use it.
My question is where can I find the upf plugin documentation? I am struggling to read the source code so I hope there is some sort of documentation anywhere on how to use it.

**Comment by RoadRunnr** [comment]
Unfortunately no one had had the time to write a documentation yet.
The only way to get started is to read check the included startup.conf and init.conf.

You also need a CUPS enable PGW/GGSN or a SMF. Without the control path instance, a UPF instance can not be used.

For the PGW/GGSN you can use ergw [1]. But as for documentation for it, most the same as said above applied.

1: https://github.com/travelping/ergw

**Comment by Twig96** [comment]
I already checked both startup and init files. The first is nothing new from vpp while the second just list some command to use in the vpp interface to try some upf operations (btw is there a way to start vpp by giving as command line argument the init.conf file to perform those operations?).

So I understand that there is no documentation for both upf and ergw but let me understand, through the ergw I should setup a PGW instance from which I can generate GTP packets to inject in my upf right?

What about SMF instead? Any advice on how to setup an instance of it and in particular to inject PFCP packets in upf? 

Thanks in advance.
