### ISSUE TITLE
An error occurred during the upf working with 5gc

### ISSUE THREAD

**Issue by CnaZhao** [travelping/vpp#71]

**Comment by CnaZhao** [comment]
HI:
on branch feature/2001/upf, i make it working with 5gc(not include upf).But an error occurred when handling PFCP_SESSION_ESTABLISHMENT_REQUEST msg. In build_sx_rules function ,
    /* create UE IP route from SGi Network Instance into Session */

    /*
     * From 3GPP TS 29.244 version 14.3.0, Table 7.5.2.2-2
     *
     * NOTE 2: When a Local F-TEID is provisioned in the PDI, the
     *         Network Instance shall relate to the IP address of
     *         the F-TEID. Otherwise, the Network Instance shall
     *         relate to the UE IP address.
     */
    if (!(pdr->pdi.fields & F_PDI_LOCAL_F_TEID) &&
	pdr->pdi.fields & F_PDI_UE_IP_ADDR)
      {
	ue_ip_t ue_ip;
	u8 is_dst = ! !(pdr->pdi.ue_addr.flags & IE_UE_IP_ADDRESS_SD);//1

	if (pdr->pdi.ue_addr.flags & IE_UE_IP_ADDRESS_V4)
	  {
	    ip46_address_set_ip4 (&ue_ip.addr, &pdr->pdi.ue_addr.ip4);
	    ue_ip.fib_index =
	      upf_fib_index_by_sw_if_index (sw_if_index, 1 /* is_ip4 */);
	    ue_ip.sw_if_index = sw_if_index;

	    clib_warning("UP FIB Idx %u, sw_if_index %u",
			 ue_ip.fib_index, ue_ip.sw_if_index);
	    rules_add_ue_ip(pending, FIB_PROTOCOL_IP4, &ue_ip, is_dst);
	  }

But my downlink pdr has no network instance,so sw_if_index = oxffff ffff.Then an error occurred.

So what is my problem?

**Comment by RoadRunnr** [comment]
That is a design decision in the current version of the UPF plugin that the Network Instance IE in PDIs is mandatory with this UPF plugin.

I hesitate to call this a bug. The current behavior is IMHO well within the limits of the specification. The NWI in PDIs is marked optional, but the notes give an example list when it becomes mandatory;
> NOTE 1: The Network Instance parameter is needed e.g. in the following cases:
>  - PGW/TDF UP function supports multiple PDNs with overlapping IP addresses; 
> ....

So for this UPF, that list is extended with: "- when the VPP UPF is used"

**Comment by CnaZhao** [comment]
hi:
Yes.got it.
Thank you very much!
