### ISSUE TITLE
PFCP lookup and highest PDR searching

### ISSUE THREAD

**Issue by Vivek-anand-jain** [travelping/vpp#78]
Hi :)

How PFCP session lookup is happening on DL/UL packet arrival? Also, aren't you using list data structure to perform highest precedence PDR searching? If that's the case, isn't that compute intensive on data path?

Please correct me if I'm wrong.

**Comment by RoadRunnr** [comment]
PFCP session lookup is happening on TEID, that is using a hash table.

But the ACL scanning of a PDRs is indeed running over the of all PDRs of that session. With many PDRs that would indeed be compute intensive. This is partly mitigated by using the flow match to store the PDR and reuse that on subsequent packets.
