### ISSUE TITLE
UPF association is not removed correctly

### ISSUE THREAD

**Issue by apssoft** [travelping/vpp#79]
The UPF association is deleted for several reasons, including heartbeat timeout.
However, this association remains in the output of the command `show upf association '.

In addition, multiple PFCP Association Setup Request packets are received from an SMF node.
Multiple associations for this node are displayed in the output of the command `show upf association '.

```
vpp# show upf association
Node: 10.200.200.1
  Recovery Time Stamp: 2020/07/17 10:47:14:000
  Sessions: 0
Node: 10.200.200.1
  Recovery Time Stamp: 2020/07/17 10:47:56:000
  Sessions: 0
vpp#
```

We think this is a bug.

**Comment by jojo-simida** [comment]
pfcp_release_association (upf_node_assoc_t * n)
{
......
pool_put (gtm->nodes, n);  //add this
}

**Comment by apssoft** [comment]
Thank you for your quick response.
We can have resolved this issue according to the patch.

**Comment by RoadRunnr** [comment]
@ivan4th is this still a problem with the latest dev version?

**Comment by ivan4th** [comment]
@RoadRunnr I think it is not, but will check

**Comment by jinboc** [comment]
it's still a problem

**Comment by RoadRunnr** [comment]
wrong project, active development was moved to the upg-vpp repository.
