### ISSUE TITLE
Is it convenient to provide a PCAP file of N4 protocol?

### ISSUE THREAD

**Issue by yongshouwang** [travelping/vpp#82]
Hello,：
       I am learning traveling upf, and N4 protocol. 
       Is it convenient to provide a PCAP file of N4 protocol? 
       thank you very much!

**Comment by RoadRunnr** [comment]
You can run the test suite from the https://github.com/travelping/ergw project and capture the N4 traffic it generates.

**Comment by yongshouwang** [comment]
thanks
