### ISSUE TITLE
How to build upf-plugin

### ISSUE THREAD

**Issue by msszzj** [travelping/vpp#91]
-- Checking for module 'libhs'
--   No package 'libhs' found
-- Hyperscan not found - GTP UPF disabled
 what's wrong

**Comment by Shaligram** [comment]
I think you need to install hyperscan-devel. that's how I got /usr/lib64/libhs.so

**Comment by msszzj** [comment]
Thank you very much.
I also modified CMakeLists.txt：
#pkg_check_modules(HS libhs)
find_path(HS_INCLUDE_DIRS NAMES hs/hs.h)
find_library(HS_LIBRARIES NAMES hs)
IF (HS_INCLUDE_DIRS AND HS_LIBRARIES)
    SET(HS_FOUND TRUE)
ENDIF (HS_INCLUDE_DIRS AND HS_LIBRARIES)
