### ISSUE TITLE
icmp packet reply dropped by upf

### ISSUE THREAD

**Issue by zhonglin6666** [travelping/vpp#92]
case:
   UE 60.60.0.1
   RAN 172.16.245.125
   UPF CP     EPC  172.16.245.49
   DN  172.16.245.132

 After succeed to establish PDU Session，UE send icmp request to DN with TEID 1，
 DN receive icmp packet, and reply to UPF
 UPF receive icmp，not access to upf function，but drop

**Comment by RoadRunnr** [comment]
In order so even start thinking about, please include:
* your VPP init.conf,
* a PCAP of the GTP side
* a PCAP of the PFCP communication

**Comment by RoadRunnr** [comment]
BTW: the project moved to https://github.com/travelping/upg-vpp, please use the latest version there and open a bug there.

**Comment by zhonglin6666** [comment]
THX!
UE Send icmp packet, trace as follows:
   dpdk-input  -->
   ethernet-input -->
   ip4-input  -->
   ip4-lookup -->
   ip4-local  -->
   ip4-udp-lookup -->
     upf-gtpu4-input  -->
     upf-ip4-flow-process  -->
     upf-ip4-classify  -->
     upf-ip4-input -->
     upf-ip4-forward  --> 
   ip4-input  -->
   ip4-lookup -->
   ip4-rewrite  -->
   epc-output  -->
   epc-tx

  but，UPF receive icmp reply trace as this:
    dpdk-input
    ethernet-input
     ip4-input
     ip4-lookup
     ip4-drop

 Can you tell me the right reply trace ?

 THX!

**Comment by zhonglin6666** [comment]
success! UPF forward icmp reply to RAN
