### ISSUE TITLE
Bidirectional SDF Filters maybe not support ?

### ISSUE THREAD

**Issue by jinboc** [travelping/vpp#96]
Bidirectional SDF Filters
The CP function may provision bidirectional SDF Filters in the UP function (see clause 8.2.5), i.e. SDF Filters that may be associated to both uplink and downlink PDRs of a same PFCP/N4 session, as follows:
-	when provisioning a bidirectional SDF Filter the first time for a PFCP/N4 session, the CP function shall provision the SDF filter definition together with a SDF Filter ID uniquely identifying the SDF Filter among all the SDF Filters provisioned for a given PFCP/N4 Session;
-	the CP function may then provision a PDR for the same PFCP/N4 session but the opposite direction, by provisioning the SDF Filter ID in the SDF filter ID field of the PDI, without provisioning again the SDF filter definition;
-	the UP function shall apply any modification of a bidirectional SDF Filter to all PDRs of the PFCP/N4 session making use of this SDF Filter;
-	upon deletion of a PDR making use of a bidirectional SDF Filter, the UP function shall still apply the SDF Filter for any other PDR making use of the SDF Filter.
The requirements specified for provisioning SDF filters in clause 5.2.1A.2A shall also apply when provisioning bidirectional SDF Filters.

**Comment by RoadRunnr** [comment]
1. active development of this project was moved to https://github.com/travelping/upg-vpp
2. bidirectional SDF's are not yet supported, separate SDFs for DL and UL need to be used for the moment. You can file a enhancement request on the UPG project.
